mydjango_board/mydjango_board/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),

    path("user/", include("user.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mydjango_board/user/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', auth_views.LoginView.as_view(
        template_name='user/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
]

mydjango_board/user/models.py
from django.db import models

# Create your models here.

mydjango_board/user/views.py
from django.http import HttpResponse
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def index(request):
    # print(request.user)
    print(request.session)
    print("session 확인")
    for k, v in request.session.items():
        print(k, v)

    print("Cookie 확인")
    history = request.COOKIES.get('board_history')
    print(history)
    return render(request, 'user/profile.html')


def profile(request):
    profile = {
        "이름": "신윤수",
        "별명": "ys",
    }
    result = ""

    for k, v in profile.items():
        result += f"<li>{k}: {v}</li>"

    html = f"""
        <h1>나의 정보</h1>
        <ul>
            {result}
        </ul>
    """

    # print(dir(request))
    request_attrs = dir(request)

    for attr in request_attrs:
        if attr.startswith("_"):
            continue
        print(attr, getattr(request, attr))
        print('-'*10)

    return HttpResponse(html)

mydjango_board/user/templates/user/login.html
{% extends "board/base.html" %}
{% block main %}
  <div class="container my-3">
    <form method="post" action="{% url 'user:login' %}">
      {% csrf_token %}
      <div class="fieldWrapper m-2">
        {{ form.username.label_tag }}
        <input type="text" class="form-control" name="{{ form.username.name }}" id="{{ form.username.name }}" value="{{ form.username.value|default_if_none:'' }}">
        {% for error in form.username.errors %}
          <div id="content-help" class="form-text text-danger">{{ field.errors }}</div>
        {% endfor %}
      </div>

      <div class="fieldWrapper m-2">
        {{ form.password.label_tag }}

        <input type="password" class="form-control" name="{{ form.password.name }}" id="{{ form.password.name }}" value="{{ form.password.value|default_if_none:'' }}">
        {% for error in form.password.errors %}
          <div id="content-help" class="form-text text-danger">{{ field.errors }}</div>
        {% endfor %}
      </div>

      <div class="mb-3 p-3">
        <div style="float:right">
          <button type="submit" class="btn btn-primary">로그인</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

mydjango_board/user/templates/user/profile.html
{% extends "board/base.html" %}
{% block main %}
  <div class="container">
    <div class="mt-5 contents-wrap">
      <h3 class="nav-loc">
        나의 정보
      </h3>

      <div class="container">
        {{ user }}
      </div>

    </div>
  </div>
{% endblock %}