mydjango_board/board/urls.py
from django.urls import path

from . import views

app_name = "board"

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:board_id>/', views.board_detail, name="detail"),
    path('write/', views.board_write, name="write"),
    path('<int:board_id>/edit/', views.board_edit, name="edit"),
    path('<int:board_id>/del/', views.board_delete, name='delete')
    #     path('', views.board_list, name='index'),
    #     path('<int:board_id>/',
    #          views.board_detail,
    #          name="board_detail"),
    #     path('comments/',
    #          views.comment_list,
    #          name="comment_list"),
]

mydjango_board/mydjango_board/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),

    path("user/", include("user.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mydjango_board/user/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', auth_views.LoginView.as_view(
        template_name='user/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
]

mydjango_board/board/models.py
from django.db import models

# Create your models here.
from django.core import validators


class Board(models.Model):
    id = models.AutoField(primary_key=True)

    title = models.CharField(max_length=255, validators=[
        validators.MinLengthValidator(2, "최소 세 글자 이상은 입력해주셔야 합니다.")
    ])
    author = models.CharField(max_length=255)
    content = models.TextField(validators=[
        validators.MinLengthValidator(10, "최소 10글자 이상은 입력해주셔야 합니다."),
    ])  # Text

    is_delete = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @classmethod
    def get_active_list(cls):
        return cls.objects.filter(is_delete=False)

    @property
    def is_active(self):
        return not self.is_delete


class Comment(models.Model):
    content = models.CharField(max_length=255)
    board = models.ForeignKey("Board", on_delete=models.SET_NULL,
                              null=True,)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

mydjango_board/board/forms.py
from django import forms
from .models import Board, Comment


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._widget_update()

    class Meta:
        model = Comment
        fields = ["content"]

    def _widget_update(self):
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class BoardForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._widget_update()

    class Meta:
        model = Board
        fields = ["title", "content", "author"]
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': "제목을 입력해주세요."
                }
            )
        }

    def _widget_update(self):
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

mydjango_board/board/views.py
import json

from django.http import Http404
from .forms import CommentForm
from .forms import BoardForm
from django.urls import reverse
from django.shortcuts import redirect
from django.http import HttpResponse
from django.shortcuts import render

from .models import Board, Comment

# TODO:
"""
1. board_detail에서 댓글을 달 수 있는 form 태그와 input tag 만들기

2. form이 submit 되면 요청을 받을 url과 view function 만들기
    - 1. form에 입력값이 빈 값이면, error를 담아서 html 보내기
    - 2. form에 입력값이 타당하면, 저장하고 상세페이지 다시 보여주기
     
3. (2)에서 만들어진 url로 (1)의 form에 action 속성에 url기록하기.
"""


def index(request):
    board_list = Board.get_active_list().prefetch_related('comment_set').all()

    return render(request, "board/index.html",
                  {'board_list': board_list})


def board_detail(request, board_id):
    board = Board.objects.get(pk=board_id)

    board_history = request.session.get('board_history')
    if not board_history:
        request.session['board_history'] = []
    request.session['board_history'] += [board_id]

    if not (board and board.is_active):
        return Http404("요청하신 페이지가 없습니다.")

    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            Comment(
                content=data['content'],
                board_id=board_id
            ).save()
            return redirect(reverse('board:detail',
                                    kwargs={'board_id': board_id}))

    resp = render(request,
                  "board/detail.html",
                  {'board': board, 'form': form})

    history = request.COOKIES.get('board_history')
    if not history:
        history = []
        history = json.dumps(history)
    history = json.loads(history)
    history += [board_id]
    resp.set_cookie('board_history', json.dumps(history))

    return resp


# def board_detail(request, board_id):
#     errors = []
#     if request.method == 'POST':
#         data = request.POST
#         content = data.get('comment')
#         if content:
#             comment = Comment(
#                 content=content,
#                 board_id=board_id
#             )
#             comment.save()
#         else:
#             errors.append("comment가 비어 있습니다.")

#     board = Board.objects.get(pk=board_id)

#     return render(request,
#                   "board/detail.html",
#                   {'board': board, 'errors': errors})


def board_write(request):
    form = BoardForm()
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('board:index'))

    return render(request,
                  "board/write.html",
                  {'form': form})


def board_edit(request, board_id):
    board = Board.objects.get(id=board_id)
    form = BoardForm(initial={
        'title': board.title,
        'content': board.content,
        'author': board.author
    })
    if request.method == 'POST':
        form = BoardForm(request.POST)

        if form.is_valid():
            board.title = form.cleaned_data['title']
            board.content = form.cleaned_data['content']
            board.author = form.cleaned_data['author']
            board.save()
            return redirect(reverse('board:detail', kwargs={
                'board_id': board_id
            }))
    return render(request,
                  "board/edit.html",
                  {'form': form})


def board_delete(request, board_id):
    board = Board.objects.get(id=board_id)
    board.is_delete = True
    board.save()
    return redirect(reverse('board:index'))


# def board_write(request):
#     if request.method == 'POST':
#         # save model
#         data = request.POST
#         title = data.get('title')
#         content = data.get('content')
#         board = Board(
#             title=title,
#             content=content,
#             author=request.user
#         )
#         board.save()
#         # 문제 X -> index페이지로 이동

#         return redirect(reverse('board:index'))
#     return render(request,
#                   "board/write.html",)

# def index(request):
#     # return HttpResponse("Hello World, I am Younsoo!")
#     sample_list = range(10)

#     return render(request, 'board/index.html',
#                   {'name': '유저', 'sample': sample_list})


# """
# board_list라는 view 함수를 만들고 /board 로 접속하면
# 게시글에 대한 전체 게시글을 리스트 (HTML: ul, li 태그 이용)로 보여주세요.
# """


# def board_list(request):
#     qs = Board.objects.all()

#     html = ""
#     for board in qs:
#         html += f"<li><a href='/board/{board.id}'>\
#             {board.title}\
#                 </a></li>"
#     html = f"<ul>{html}</ul>"

#     return HttpResponse(html)


# """/board/comments로 접속하면 모든 댓글을 조회하도록 해주세요.
#     조회내용에 대한 형식은 다음과 같습니다.
#     (<ul>
#     <li>코멘트id | 댓글내용 | board_id </li>
#     …
#     </ul>)
# """


# def comment_list(request):
#     qs = Comment.objects.all()

#     html = ""
#     for comment in qs:
#         html += f"<li>{comment.id} | \
#             {comment.content} | {comment.board_id} </li>"
#     html = f"<ul>{html}</ul>"

#     return HttpResponse(html)


# """
# 각 게시글을 클릭 가능하게 해주시고,
# 클릭에 대한 url은 /board/<id> 로 해주세요.
# (<id>는 board에 대한 id(pk)값
# """

# # (*args, **kwargs)


# def board_detail(request, board_id):
#     qs = Board.objects.get(id=board_id)
#     comment_list = qs.comment_set.all()

#     html = f"<h1>{qs.title}</h1> \
#         <div>{qs.content}</div>"

#     html += "<ul>"
#     for comment in comment_list:
#         html += f"<li>{comment.content}</li>"
#     html += "</ul>"

#     return HttpResponse(html)

mydjango_board/board/templates/board/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      main > .container {
        padding: 60px 15px 0;
      }
    </style>
  </head>

  <body>

    {% include './partials/header.html' %}

    <!-- Begin page content -->
    <main class="flex-shrink-0">
      {% block main %}{% endblock %}
    </main>

    {% include './partials/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>

</html>

mydjango_board/board/templates/board/detail.html
{% extends './base.html' %}
{% block main %}
  <div class="container">
    <h3>상세 게시글</h3>

    <div class="my-5">
      <div class="my-2">
        <h5>{{ board.title }}</h5>
      </div>

      <div style="border:1px solid black; padding:2px; min-height:200px;">
        {{ board.content }}
      </div>

      <a href="{% url 'board:edit' board.id %}" class='btn btn-success'>
        수정
      </a>
      <a href="{% url 'board:delete' board.id %}" class='btn btn-primary'>삭제</a>
    </div>

    <div class="mv-4">
      <form action="" method="POST" style="display:flex; flex-direction:row;">
        {% csrf_token %}
        {% comment %} <input type="text" name="comment" id="" class='form-control'> {% endcomment %}
        {% for field in form %}
            {{ field }}
        {% endfor %}
        <button type="submit" class="btn btn-primary" style="min-width:100px;">
          댓글작성
        </button>
      </form>

      {% for error in field.errors %}
        <div id="content-help" class="form-text text-danger">
          {{ field.errors }}
        </div>
      {% endfor %}

    </div>

    <div class="my-4">
      <ul class="list-group">
        {% for comment in board.comment_set.all %}
          <li class="list-group-item">{{ comment.content }}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

mydjango_board/board/templates/board/edit.html
{% extends "./base.html" %}
{% block main %}
  <div class="container">
    <form action="" method="POST">
      {% csrf_token %}

      {% for field in form %}
        <div class="fieldWrapper m-2">
          {{ field.label_tag }}
          {{ field }}

          {% for error in field.errors %}
            <div id="content-help" class="form-text text-danger">
              {{ field.errors }}
            </div>
          {% endfor %}
        </div>
      {% endfor %}

      <button type="submit">제출</button>
    </form>
  </div>
{% endblock %}

mydjango_board/board/templates/board/index.html
{% extends "./base.html" %}
{% block main %}

  <div class="container">

    <div class="my-5" style="display:flex; justify-content:flex-end;">
      <a href="{% url 'board:write' %}" class="btn btn-primary">
        글쓰기
      </a>
    </div>

    <ol class="list-group list-group-numbered">
      {% for board in board_list %}
        <a href="{% url 'board:detail' board.id %}">
          <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
              <div class="fw-bold">{{ board.title }}</div>
              {{board.content}}
            </div>
            <span class="badge bg-primary rounded-pill">
              {{board.comment_set.all|length}}
            </span>
          </li>
        </a>
      {% endfor %}
    </ol>
  </div>
{% endblock %}

mydjango_board/board/templates/board/write.html
{% extends "./base.html" %}
{% block main %}
  <div class="container">
    <form action="" method="POST">
      {% csrf_token %}

      {% for field in form %}
        <div class="fieldWrapper m-2">
          {{ field.label_tag }}
          {{ field }}

          {% for error in field.errors %}
            <div id="content-help" class="form-text text-danger">
              {{ field.errors }}
            </div>
          {% endfor %}
        </div>
      {% endfor %}

      <button type="submit">제출</button>
    </form>
  </div>
{% endblock %}